/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELAS;

import ConfigDB.ConnMySQL;
import Model.Aluguel;
import Model.Carro;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class AluguelConsultaCarrosAlugados extends javax.swing.JFrame {

    ArrayList<Aluguel> arrayAluguel = new ArrayList<>();
    int i = 0;
    Login ADM;
    /**
     * Creates new form AluguelConsultaCarrosAlugados
     */
    public AluguelConsultaCarrosAlugados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        inputConsultaCarrosAlugados = new javax.swing.JTextField();
        buttonConsultaCarrosAlugados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaConsultaCarro = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        buttonGerarArquivoConsultaCarrosAlugados = new javax.swing.JButton();
        selectGeralConsultaCarrosAlugados = new javax.swing.JRadioButton();
        selectEspecConsultaCarrosAlugados = new javax.swing.JRadioButton();
        LimparConsultaCarrosAlugados = new javax.swing.JButton();
        selectConsultaCarrosAlugados = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroVeiculo = new javax.swing.JMenuItem();
        cadastroUsuario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        consultaCliente = new javax.swing.JMenuItem();
        consultaCarro = new javax.swing.JMenuItem();
        consultaUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aluguelRegistrar = new javax.swing.JMenuItem();
        menuCarrosAlugados = new javax.swing.JMenuItem();
        MenuExcluir = new javax.swing.JMenu();
        excluirCliente = new javax.swing.JMenuItem();
        excluirUsuario = new javax.swing.JMenuItem();
        excluirVeiculo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        alterarSenha = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                EscondeInputs(evt);
            }
        });

        buttonConsultaCarrosAlugados.setText("Consultar");
        buttonConsultaCarrosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultaCarrosAlugadosConsultarClientes(evt);
            }
        });

        textAreaConsultaCarro.setEditable(false);
        textAreaConsultaCarro.setColumns(20);
        textAreaConsultaCarro.setRows(5);
        jScrollPane1.setViewportView(textAreaConsultaCarro);

        jLabel1.setText("Consulta de Carros Alugados");

        buttonGerarArquivoConsultaCarrosAlugados.setText("Gerar Arquivo");
        buttonGerarArquivoConsultaCarrosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGerarArquivoConsultaCarrosAlugadosGerarArquivo(evt);
            }
        });

        buttonGroup1.add(selectGeralConsultaCarrosAlugados);
        selectGeralConsultaCarrosAlugados.setSelected(true);
        selectGeralConsultaCarrosAlugados.setText("Geral");
        selectGeralConsultaCarrosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectGeralConsultaCarrosAlugadosConsultaClienteGeral(evt);
            }
        });

        buttonGroup1.add(selectEspecConsultaCarrosAlugados);
        selectEspecConsultaCarrosAlugados.setText("Específica");
        selectEspecConsultaCarrosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEspecConsultaCarrosAlugadosConsultaClienteEspec(evt);
            }
        });

        LimparConsultaCarrosAlugados.setText("Limpar");
        LimparConsultaCarrosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparConsultaCarrosAlugados(evt);
            }
        });

        selectConsultaCarrosAlugados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placa", "CPF", "Data de entrega", "Data de devolução" }));
        selectConsultaCarrosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectConsultaCarrosAlugadosActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadastro");

        cadastroCliente.setText("Cliente");
        cadastroCliente.setName("cadastroCliente"); // NOI18N
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteCadastroCliente(evt);
            }
        });
        jMenu1.add(cadastroCliente);

        cadastroVeiculo.setText("Carro");
        cadastroVeiculo.setName("cadastroVeiculo"); // NOI18N
        cadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroVeiculoCadastroCarro(evt);
            }
        });
        jMenu1.add(cadastroVeiculo);

        cadastroUsuario.setText("Usuário");
        cadastroUsuario.setName("cadastroUsuario"); // NOI18N
        cadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroUsuarioCadastroUsuario(evt);
            }
        });
        jMenu1.add(cadastroUsuario);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Consulta");

        consultaCliente.setText("Cliente");
        consultaCliente.setName("consultaCliente"); // NOI18N
        consultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaClienteConsultaCliente(evt);
            }
        });
        jMenu4.add(consultaCliente);

        consultaCarro.setText("Carro");
        consultaCarro.setName("consultaCarro"); // NOI18N
        consultaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaCarroConsultaCarro(evt);
            }
        });
        jMenu4.add(consultaCarro);

        consultaUsuario.setText("Usuário");
        consultaUsuario.setName("consultaUsuario"); // NOI18N
        consultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaUsuarioConsultaUsuario(evt);
            }
        });
        jMenu4.add(consultaUsuario);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Aluguel");

        aluguelRegistrar.setText("Registrar");
        aluguelRegistrar.setName("aluguelRegistrar"); // NOI18N
        aluguelRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aluguelRegistrarAluguelRegistrar(evt);
            }
        });
        jMenu2.add(aluguelRegistrar);

        menuCarrosAlugados.setBackground(new java.awt.Color(153, 153, 153));
        menuCarrosAlugados.setText("Carros Alugados");
        menuCarrosAlugados.setToolTipText("");
        jMenu2.add(menuCarrosAlugados);

        jMenuBar1.add(jMenu2);

        MenuExcluir.setText("Excluir");
        MenuExcluir.setName(""); // NOI18N

        excluirCliente.setText("Cliente");
        excluirCliente.setName("excluirCliente"); // NOI18N
        excluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClienteExcluirCliente(evt);
            }
        });
        MenuExcluir.add(excluirCliente);

        excluirUsuario.setText("Usuário");
        excluirUsuario.setName("excluirUsuario"); // NOI18N
        excluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUsuarioExcluirUsuario(evt);
            }
        });
        MenuExcluir.add(excluirUsuario);

        excluirVeiculo.setText("Carro");
        excluirVeiculo.setName("excluirVeiculo"); // NOI18N
        excluirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirVeiculoExcluirCarro(evt);
            }
        });
        MenuExcluir.add(excluirVeiculo);

        jMenuBar1.add(MenuExcluir);

        jMenu5.setText("...");

        alterarSenha.setText("Alterar Senha");
        alterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarSenhaAlterarSenha(evt);
            }
        });
        jMenu5.add(alterarSenha);

        jMenuItem3.setText("SAIR");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3Sair(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectConsultaCarrosAlugados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputConsultaCarrosAlugados)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(selectGeralConsultaCarrosAlugados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selectEspecConsultaCarrosAlugados)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(buttonGerarArquivoConsultaCarrosAlugados))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(buttonConsultaCarrosAlugados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LimparConsultaCarrosAlugados)))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectGeralConsultaCarrosAlugados)
                            .addComponent(selectEspecConsultaCarrosAlugados))
                        .addGap(20, 20, 20)
                        .addComponent(selectConsultaCarrosAlugados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(inputConsultaCarrosAlugados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonConsultaCarrosAlugados)
                            .addComponent(LimparConsultaCarrosAlugados))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGerarArquivoConsultaCarrosAlugados)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConsultaCarrosAlugadosConsultarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultaCarrosAlugadosConsultarClientes

        textAreaConsultaCarro.setText("");

        String sql = null;
        Connection conexao = null;
        arrayAluguel.clear();

        if (selectGeralConsultaCarrosAlugados.isSelected()) {

            sql = "SELECT aluguel.placa, carro.fabricante, carro.modelo, carro.ano, "
                    + "cliente.nome, aluguel.cpf, aluguel.data_entrega, "
                    + "aluguel.data_devolucao "
                    + "FROM aluguel "
                    + "INNER JOIN cliente ON aluguel.cpf = cliente.cpf "
                    + "INNER JOIN carro ON aluguel.placa = carro.placa;";
            conexao = ConnMySQL.conectar();

        } else {

            String itemSelecionado = null;
            
            switch (selectConsultaCarrosAlugados.getSelectedItem().toString()){
                
                case "Data de entrega":
                    itemSelecionado = "aluguel.data_entrega";
                break;
                
                case "Data de devolução":
                    itemSelecionado = "aluguel.data_devolucao";
                break;
                
                case "CPF":
                    itemSelecionado = "aluguel.cpf";
                break;
                
                case "Placa":
                    itemSelecionado = "aluguel.placa";
                break;
            }

            
            
            String valorDigitado = inputConsultaCarrosAlugados.getText();

            sql = "SELECT aluguel.placa, carro.fabricante, carro.modelo, carro.ano, "
                    + "cliente.nome, aluguel.cpf, aluguel.data_entrega, "
                    + "aluguel.data_devolucao "
                    + "FROM aluguel "
                    + "INNER JOIN cliente ON aluguel.cpf = cliente.cpf "
                    + "INNER JOIN carro ON aluguel.placa = carro.placa "
                    + "WHERE " + itemSelecionado + " LIKE '" + valorDigitado + "';";
            conexao = ConnMySQL.conectar();
        }

        try {
            Statement statement = conexao.createStatement();
            ResultSet result = statement.executeQuery(sql);

            while (result.next()) {
                
                Aluguel a = new Aluguel(
                    result.getString("aluguel.placa"),
                    result.getString("aluguel.cpf"),
                    result.getString("aluguel.data_entrega"),
                    result.getString("aluguel.data_devolucao"),
                    result.getString("cliente.nome"),
                    result.getString("carro.fabricante"),
                    result.getString("carro.modelo"),
                    result.getInt("carro.ano")
                           
                );

                arrayAluguel.add(a);

                textAreaConsultaCarro.setText(textAreaConsultaCarro.getText() 
                    + "\nPlaca: " + a.getPlaca() + "\n"
                    + "Fabricante: " + a.getFabricante() + "\n"
                    + "Modelo: " + a.getModelo() + "\n"
                    + "Ano: " + a.getAno() + "\n"  
                    + "Nome: " + a.getNome() + "\n"
                    + "CPF: " + a.getCpf() + "\n"
                    + "Data da Entrega: " + a.getData_entrega() + "\n"
                    + "Data da Devolução: " + a.getData_devolucao() + "\n\n");
            }

            conexao.close();

        } catch (SQLException throwables) {
            throwables.printStackTrace();

        } catch (Exception f) {
            System.out.println("ERRO CADASTRO: " + f);
        }
    }//GEN-LAST:event_buttonConsultaCarrosAlugadosConsultarClientes

    private void buttonGerarArquivoConsultaCarrosAlugadosGerarArquivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGerarArquivoConsultaCarrosAlugadosGerarArquivo

        i++;

        try{
            FileWriter caminho = new FileWriter("C:\\JAVA\\Relatorio_de_carros_alugados_"+ i +".txt");
            BufferedWriter arquivo = new BufferedWriter(caminho);

            arquivo.write("\n\t\tRELATÓRIO DE CARROS ALUGADOS\n\n");

            for (Aluguel a : arrayAluguel) {

                arquivo.write("\nPlaca: " + a.getPlaca() + "\n"
                    + "Fabricante: " + a.getFabricante() + "\n"
                    + "Modelo: " + a.getModelo() + "\n"
                    + "Ano: " + a.getAno() + "\n"  
                    + "Nome: " + a.getNome() + "\n"
                    + "CPF: " + a.getCpf() + "\n"
                    + "Data da Entrega: " + a.getData_entrega() + "\n"
                    + "Data da Devolução: " + a.getData_devolucao() + "\n\n");
            }

            arquivo.close();

            JOptionPane.showMessageDialog(null, "Arquivo gerado com sucesso!");

        } catch (FileNotFoundException ex) {

            System.out.println("Erro no arquivo(" + ex + ")");

        }  catch (Exception f) {
            System.out.println("ERRO CADASTRO: " + f);
        }
    }//GEN-LAST:event_buttonGerarArquivoConsultaCarrosAlugadosGerarArquivo

    private void selectGeralConsultaCarrosAlugadosConsultaClienteGeral(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectGeralConsultaCarrosAlugadosConsultaClienteGeral
        selectConsultaCarrosAlugados.setVisible(false);
        inputConsultaCarrosAlugados.setVisible(false);
    }//GEN-LAST:event_selectGeralConsultaCarrosAlugadosConsultaClienteGeral

    private void selectEspecConsultaCarrosAlugadosConsultaClienteEspec(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEspecConsultaCarrosAlugadosConsultaClienteEspec
        selectConsultaCarrosAlugados.setVisible(true);
        inputConsultaCarrosAlugados.setVisible(true);
    }//GEN-LAST:event_selectEspecConsultaCarrosAlugadosConsultaClienteEspec

    private void LimparConsultaCarrosAlugados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparConsultaCarrosAlugados
        textAreaConsultaCarro.setText("");
        inputConsultaCarrosAlugados.setText("");
        arrayAluguel.clear();
    }//GEN-LAST:event_LimparConsultaCarrosAlugados

    private void selectConsultaCarrosAlugadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectConsultaCarrosAlugadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectConsultaCarrosAlugadosActionPerformed

    private void EscondeInputs(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_EscondeInputs
       
        if (ADM.adm == 0) {

            MenuExcluir.setVisible(false);
            cadastroUsuario.setVisible(false);
            consultaUsuario.setVisible(false);
        }
        
        selectConsultaCarrosAlugados.setVisible(false);
        inputConsultaCarrosAlugados.setVisible(false);
    }//GEN-LAST:event_EscondeInputs

    private void cadastroClienteCadastroCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteCadastroCliente
        CadastroCliente cadastroCliente = new CadastroCliente();

        cadastroCliente.setVisible(true);
        
        cadastroCliente.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_cadastroClienteCadastroCliente

    private void cadastroVeiculoCadastroCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroVeiculoCadastroCarro
        CadastroCarro cadastroCarro = new CadastroCarro();

        cadastroCarro.setVisible(true);
        
        cadastroCarro.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_cadastroVeiculoCadastroCarro

    private void cadastroUsuarioCadastroUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroUsuarioCadastroUsuario
        CadastroUsuario cadastroUsuario = new CadastroUsuario();

        cadastroUsuario.setVisible(true);
        
        cadastroUsuario.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_cadastroUsuarioCadastroUsuario

    private void consultaClienteConsultaCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaClienteConsultaCliente
        ConsultaCliente consultaCliente = new ConsultaCliente();

        consultaCliente.setVisible(true);
        
        consultaCliente.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_consultaClienteConsultaCliente

    private void consultaCarroConsultaCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaCarroConsultaCarro
        ConsultaCarro consultaCarro = new ConsultaCarro();

        consultaCarro.setVisible(true);
        
        consultaCarro.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_consultaCarroConsultaCarro

    private void consultaUsuarioConsultaUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaUsuarioConsultaUsuario
        ConsultaUsuario consultaUsuario = new ConsultaUsuario();

        consultaUsuario.setVisible(true);
        
        consultaUsuario.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_consultaUsuarioConsultaUsuario

    private void aluguelRegistrarAluguelRegistrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aluguelRegistrarAluguelRegistrar
        AluguelRegistrar aluguelRegistrar = new AluguelRegistrar();

        aluguelRegistrar.setVisible(true);
        
        aluguelRegistrar.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_aluguelRegistrarAluguelRegistrar

    private void excluirClienteExcluirCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClienteExcluirCliente
        ExcluirCliente excluirCliente = new ExcluirCliente();

        excluirCliente.setVisible(true);
        
        excluirCliente.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_excluirClienteExcluirCliente

    private void excluirUsuarioExcluirUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirUsuarioExcluirUsuario
        ExcluirUsuario excluirUsuario = new ExcluirUsuario();

        excluirUsuario.setVisible(true);
        
        excluirUsuario.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_excluirUsuarioExcluirUsuario

    private void excluirVeiculoExcluirCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirVeiculoExcluirCarro
        ExcluirCarro excluirCarro = new ExcluirCarro();

        excluirCarro.setVisible(true);
        
        excluirCarro.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_excluirVeiculoExcluirCarro

    private void alterarSenhaAlterarSenha(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarSenhaAlterarSenha
        AlterarSenha alterarSenha = new AlterarSenha();

        alterarSenha.setVisible(true);
        
        alterarSenha.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_alterarSenhaAlterarSenha

    private void jMenuItem3Sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3Sair
        Login login = new Login();

        login.setVisible(true);
        
        login.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_jMenuItem3Sair

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AluguelConsultaCarrosAlugados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AluguelConsultaCarrosAlugados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AluguelConsultaCarrosAlugados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AluguelConsultaCarrosAlugados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AluguelConsultaCarrosAlugados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimparConsultaCarrosAlugados;
    private javax.swing.JMenu MenuExcluir;
    private javax.swing.JMenuItem alterarSenha;
    private javax.swing.JMenuItem aluguelRegistrar;
    private javax.swing.JButton buttonConsultaCarrosAlugados;
    private javax.swing.JButton buttonGerarArquivoConsultaCarrosAlugados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroUsuario;
    private javax.swing.JMenuItem cadastroVeiculo;
    private javax.swing.JMenuItem consultaCarro;
    private javax.swing.JMenuItem consultaCliente;
    private javax.swing.JMenuItem consultaUsuario;
    private javax.swing.JMenuItem excluirCliente;
    private javax.swing.JMenuItem excluirUsuario;
    private javax.swing.JMenuItem excluirVeiculo;
    private javax.swing.JTextField inputConsultaCarrosAlugados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuCarrosAlugados;
    private javax.swing.JComboBox<String> selectConsultaCarrosAlugados;
    private javax.swing.JRadioButton selectEspecConsultaCarrosAlugados;
    private javax.swing.JRadioButton selectGeralConsultaCarrosAlugados;
    private javax.swing.JTextArea textAreaConsultaCarro;
    // End of variables declaration//GEN-END:variables
}
