/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELAS;

import ConfigDB.ConnMySQL;
import Model.User;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class ExcluirUsuario extends javax.swing.JFrame {

    ArrayList<User> arrayUser = new ArrayList<>();

    /**
     * Creates new form ExcluirUsuario
     */
    public ExcluirUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputConsultaUsuario = new javax.swing.JTextField();
        consultaUsuarioLimpar = new javax.swing.JButton();
        buttonConsultaUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaConsultaUsuario = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        buttonExcluirUsuario = new javax.swing.JButton();
        selectConsultaUsuario = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroVeiculo = new javax.swing.JMenuItem();
        cadastroUsuario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        consultaCliente = new javax.swing.JMenuItem();
        consultaCarro = new javax.swing.JMenuItem();
        consultaUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aluguelRegistrar = new javax.swing.JMenuItem();
        menuCarrosAlugados = new javax.swing.JMenuItem();
        MenuExcluir = new javax.swing.JMenu();
        excluirCliente = new javax.swing.JMenuItem();
        excluirUsuario = new javax.swing.JMenuItem();
        excluirVeiculo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        alterarSenha = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consultaUsuarioLimpar.setText("Limpar");
        consultaUsuarioLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaUsuarioLimparLimparConsulta(evt);
            }
        });

        buttonConsultaUsuario.setText("Consultar");
        buttonConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultaUsuarioConsultarClientes(evt);
            }
        });

        textAreaConsultaUsuario.setEditable(false);
        textAreaConsultaUsuario.setColumns(20);
        textAreaConsultaUsuario.setRows(5);
        jScrollPane1.setViewportView(textAreaConsultaUsuario);

        jLabel1.setText("Excluir de Usuários");

        buttonExcluirUsuario.setText("Excluir");
        buttonExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirUsuarioGerarArquivo(evt);
            }
        });

        selectConsultaUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Login", "Nome", "CPF" }));
        selectConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectConsultaUsuarioActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadastro");

        cadastroCliente.setText("Cliente");
        cadastroCliente.setName("cadastroCliente"); // NOI18N
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteCadastroCliente(evt);
            }
        });
        jMenu1.add(cadastroCliente);

        cadastroVeiculo.setText("Carro");
        cadastroVeiculo.setName("cadastroVeiculo"); // NOI18N
        cadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroVeiculoCadastroCarro(evt);
            }
        });
        jMenu1.add(cadastroVeiculo);

        cadastroUsuario.setText("Usuário");
        cadastroUsuario.setName("cadastroUsuario"); // NOI18N
        cadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroUsuarioCadastroUsuario(evt);
            }
        });
        jMenu1.add(cadastroUsuario);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Consulta");

        consultaCliente.setText("Cliente");
        consultaCliente.setName("consultaCliente"); // NOI18N
        consultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaClienteConsultaCliente(evt);
            }
        });
        jMenu4.add(consultaCliente);

        consultaCarro.setText("Carro");
        consultaCarro.setName("consultaCarro"); // NOI18N
        consultaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaCarroConsultaCarro(evt);
            }
        });
        jMenu4.add(consultaCarro);

        consultaUsuario.setText("Usuário");
        consultaUsuario.setName("consultaUsuario"); // NOI18N
        consultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaUsuarioConsultaUsuario(evt);
            }
        });
        jMenu4.add(consultaUsuario);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Aluguel");

        aluguelRegistrar.setText("Registrar");
        aluguelRegistrar.setName("aluguelRegistrar"); // NOI18N
        aluguelRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aluguelRegistrarAluguelRegistrar(evt);
            }
        });
        jMenu2.add(aluguelRegistrar);

        menuCarrosAlugados.setText("Carros Alugados");
        menuCarrosAlugados.setToolTipText("");
        menuCarrosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarrosAlugadosConsultaCarrosAlugados(evt);
            }
        });
        jMenu2.add(menuCarrosAlugados);

        jMenuBar1.add(jMenu2);

        MenuExcluir.setText("Excluir");
        MenuExcluir.setName(""); // NOI18N

        excluirCliente.setText("Cliente");
        excluirCliente.setName("excluirCliente"); // NOI18N
        excluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClienteExcluirCliente(evt);
            }
        });
        MenuExcluir.add(excluirCliente);

        excluirUsuario.setBackground(new java.awt.Color(153, 153, 153));
        excluirUsuario.setText("Usuário");
        excluirUsuario.setName("excluirUsuario"); // NOI18N
        MenuExcluir.add(excluirUsuario);

        excluirVeiculo.setText("Carro");
        excluirVeiculo.setName("excluirVeiculo"); // NOI18N
        excluirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirVeiculoExcluirCarro(evt);
            }
        });
        MenuExcluir.add(excluirVeiculo);

        jMenuBar1.add(MenuExcluir);

        jMenu5.setText("...");

        alterarSenha.setText("Alterar Senha");
        alterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarSenhaAlterarSenha(evt);
            }
        });
        jMenu5.add(alterarSenha);

        jMenuItem3.setText("SAIR");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3Sair(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectConsultaUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputConsultaUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(buttonExcluirUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(337, 337, 337)
                                .addComponent(buttonConsultaUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(consultaUsuarioLimpar)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(selectConsultaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(inputConsultaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonConsultaUsuario)
                            .addComponent(consultaUsuarioLimpar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExcluirUsuario)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaUsuarioLimparLimparConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaUsuarioLimparLimparConsulta
        textAreaConsultaUsuario.setText("");
        inputConsultaUsuario.setText("");
        arrayUser.clear();
    }//GEN-LAST:event_consultaUsuarioLimparLimparConsulta

    private void buttonConsultaUsuarioConsultarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultaUsuarioConsultarClientes

        textAreaConsultaUsuario.setText("");

        if (inputConsultaUsuario.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Informe o usuário que deseja excluir!");

        } else {

            String sql = null;
            Connection conexao = null;
            arrayUser.clear();

            String itemSelecionado = selectConsultaUsuario.getSelectedItem().toString();

            String valorDigitado = inputConsultaUsuario.getText();

            sql = "SELECT * FROM usuario WHERE " + itemSelecionado + " LIKE '" + valorDigitado + "' ORDER BY login ASC ";
            conexao = ConnMySQL.conectar();

            try {
                Statement statement = conexao.createStatement();
                ResultSet result = statement.executeQuery(sql);

                while (result.next()) {

                    User u = new User(
                            result.getString("login"),
                            result.getString("nome"),
                            result.getString("cpf"),
                            result.getInt("admin")
                    );

                    String adm = null;

                    if (u.getAdmin() == 1) {

                        adm = "ADMINISTRADOR";
                    } else {

                        adm = "COMUM";
                    }

                    arrayUser.add(u);

                    textAreaConsultaUsuario.setText(textAreaConsultaUsuario.getText()
                            + "\nUsuario: " + u.getLogin() + "\n"
                            + "Nome: " + u.getNome() + "\n"
                            + "CPF: " + u.getCpf() + "\n"
                            + "Tipo de usuário " + adm + "\n\n");

                }

                conexao.close();

            } catch (SQLException throwables) {
                throwables.printStackTrace();

            } catch (Exception f) {
                System.out.println("ERRO EXCLUSÃO: " + f);
            }

        }

    }//GEN-LAST:event_buttonConsultaUsuarioConsultarClientes

    private void buttonExcluirUsuarioGerarArquivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirUsuarioGerarArquivo

        if (inputConsultaUsuario.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Informe o usuário que deseja excluir!");
        } else {

            if (textAreaConsultaUsuario.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "Informe o usuário que deseja excluir!");

            } else {

                int i = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja efetuar a exclusão?", "Confirmação", JOptionPane.YES_NO_OPTION);

                if (i == JOptionPane.YES_OPTION) {

                    try {

                        Connection conexao = ConnMySQL.conectar();

                        String itemSelecionado = selectConsultaUsuario.getSelectedItem().toString();

                        String valorDigitado = inputConsultaUsuario.getText();

                        String sql = "DELETE FROM usuario WHERE " + itemSelecionado + " LIKE '" + valorDigitado + "'";
                        PreparedStatement statement = conexao.prepareStatement(sql);

                        int linhas = statement.executeUpdate();

                        if (linhas > 0) {
                            textAreaConsultaUsuario.setText("");
                            inputConsultaUsuario.setText("");
                            conexao.close();
                            JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso!");
                        } else {

                            JOptionPane.showMessageDialog(null, "Usuário NÃO excluído!");
                        }
                        conexao.close();

                    } catch (Exception f) {
                        System.out.println("ERRO EXCLUSÃO: " + f);
                    }

                } else {
                    textAreaConsultaUsuario.setText("");
                    inputConsultaUsuario.setText("");

                    JOptionPane.showMessageDialog(null, "Nenhum usuário excluído!");
                }
            }

        }
    }//GEN-LAST:event_buttonExcluirUsuarioGerarArquivo

    private void selectConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectConsultaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectConsultaUsuarioActionPerformed

    private void cadastroClienteCadastroCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteCadastroCliente
        CadastroCliente cadastroCliente = new CadastroCliente();

        cadastroCliente.setVisible(true);
        
        cadastroCliente.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_cadastroClienteCadastroCliente

    private void cadastroVeiculoCadastroCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroVeiculoCadastroCarro
        CadastroCarro cadastroCarro = new CadastroCarro();

        cadastroCarro.setVisible(true);
        
        cadastroCarro.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_cadastroVeiculoCadastroCarro

    private void cadastroUsuarioCadastroUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroUsuarioCadastroUsuario
        CadastroUsuario cadastroUsuario = new CadastroUsuario();

        cadastroUsuario.setVisible(true);
        
        cadastroUsuario.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_cadastroUsuarioCadastroUsuario

    private void consultaClienteConsultaCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaClienteConsultaCliente
        ConsultaCliente consultaCliente = new ConsultaCliente();

        consultaCliente.setVisible(true);
        
        consultaCliente.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_consultaClienteConsultaCliente

    private void consultaCarroConsultaCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaCarroConsultaCarro
        ConsultaCarro consultaCarro = new ConsultaCarro();

        consultaCarro.setVisible(true);
        
        consultaCarro.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_consultaCarroConsultaCarro

    private void consultaUsuarioConsultaUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaUsuarioConsultaUsuario
        ConsultaUsuario consultaUsuario = new ConsultaUsuario();

        consultaUsuario.setVisible(true);
        
        consultaUsuario.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_consultaUsuarioConsultaUsuario

    private void aluguelRegistrarAluguelRegistrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aluguelRegistrarAluguelRegistrar
        AluguelRegistrar aluguelRegistrar = new AluguelRegistrar();

        aluguelRegistrar.setVisible(true);
        
        aluguelRegistrar.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_aluguelRegistrarAluguelRegistrar

    private void menuCarrosAlugadosConsultaCarrosAlugados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarrosAlugadosConsultaCarrosAlugados
        AluguelConsultaCarrosAlugados carrosAlugados = new AluguelConsultaCarrosAlugados();

        carrosAlugados.setVisible(true);

        carrosAlugados.setLocationRelativeTo(null);  
        
        this.dispose();
    }//GEN-LAST:event_menuCarrosAlugadosConsultaCarrosAlugados

    private void excluirClienteExcluirCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClienteExcluirCliente
        ExcluirCliente excluirCliente = new ExcluirCliente();

        excluirCliente.setVisible(true);
        
        excluirCliente.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_excluirClienteExcluirCliente

    private void excluirVeiculoExcluirCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirVeiculoExcluirCarro
        ExcluirCarro excluirCarro = new ExcluirCarro();

        excluirCarro.setVisible(true);
        
        excluirCarro.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_excluirVeiculoExcluirCarro

    private void alterarSenhaAlterarSenha(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarSenhaAlterarSenha
        AlterarSenha alterarSenha = new AlterarSenha();

        alterarSenha.setVisible(true);

        alterarSenha.setLocationRelativeTo(null);  
        
        this.dispose();
    }//GEN-LAST:event_alterarSenhaAlterarSenha

    private void jMenuItem3Sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3Sair
        Login login = new Login();

        login.setVisible(true);
        
        login.setLocationRelativeTo(null);  

        this.dispose();
    }//GEN-LAST:event_jMenuItem3Sair

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuExcluir;
    private javax.swing.JMenuItem alterarSenha;
    private javax.swing.JMenuItem aluguelRegistrar;
    private javax.swing.JButton buttonConsultaUsuario;
    private javax.swing.JButton buttonExcluirUsuario;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroUsuario;
    private javax.swing.JMenuItem cadastroVeiculo;
    private javax.swing.JMenuItem consultaCarro;
    private javax.swing.JMenuItem consultaCliente;
    private javax.swing.JMenuItem consultaUsuario;
    private javax.swing.JButton consultaUsuarioLimpar;
    private javax.swing.JMenuItem excluirCliente;
    private javax.swing.JMenuItem excluirUsuario;
    private javax.swing.JMenuItem excluirVeiculo;
    private javax.swing.JTextField inputConsultaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuCarrosAlugados;
    private javax.swing.JComboBox<String> selectConsultaUsuario;
    private javax.swing.JTextArea textAreaConsultaUsuario;
    // End of variables declaration//GEN-END:variables
}
